/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AA: typeof import('./../src/components/AA.vue')['default']
    Anchor: typeof import('./../src/components/Global/Anchor.vue')['default']
    Breadcrumb: typeof import('./../src/components/Page/navbar/Breadcrumb.vue')['default']
    ButtonCreate: typeof import('./../src/components/Botton/ButtonCreate.vue')['default']
    ButtonGroupPermission: typeof import('./../src/components/Botton/ButtonGroupPermission.vue')['default']
    ButtonIconCreate: typeof import('./../src/components/Botton/ButtonIconCreate.vue')['default']
    ButtonIconTipPermission: typeof import('./../src/components/Botton/ButtonIconTipPermission.vue')['default']
    ButtonTipPermission: typeof import('./../src/components/Botton/ButtonTipPermission.vue')['default']
    DefaultTable: typeof import('./../src/components/Table/DefaultTable.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormFormLogin: typeof import('./../src/components/Form/FormLogin.vue')['default']
    FormLogin: typeof import('./../src/components/Form/FormLogin.vue')['default']
    FullScreen: typeof import('./../src/components/Page/navbar/FullScreen.vue')['default']
    GlobalSvgIcon: typeof import('./../src/components/Global/SvgIcon.vue')['default']
    HistoryLink: typeof import('./../src/components/Page/HistoryLink.vue')['default']
    Menu: typeof import('./../src/components/Page/Menu.vue')['default']
    NavBar: typeof import('./../src/components/Page/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/Global/SvgIcon.vue')['default']
    ThemeSetting: typeof import('./../src/components/Page/navbar/ThemeSetting.vue')['default']
    UserInfo: typeof import('./../src/components/Page/navbar/UserInfo.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
